### ISSUE TITLE
Declaring a validation schema other than `MappingSchema` may throw an uncaught exception

### ISSUE THREAD

**Issue by ltvolks** [Cornices/cornice#250]
The `colander.Mapping` type is the only type that has the [`unknown` attribute](http://colander.readthedocs.org/en/latest/api.html#colander.Mapping). During schema validation, this attribute is [accessed](https://github.com/mozilla-services/cornice/blob/b211e5ca0de6f26dc0f3507720efd9619edf2548/cornice/schemas.py#L150).

Therefore any otherwise valid body will thrown an exception on validation if the declared schema type is not a `colander.Mapping`. Essentially this means anything other than a `colander.MappingSchema`.

Example:
```python
import colander
from cornice.service import Service
from pyramid.config import Configurator
from webtest import TestApp


class ValidationSchema(colander.MappingSchema):
    key = colander.SchemaNode(colander.String())

class ListSchema(colander.SequenceSchema):
    key = colander.SchemaNode(colander.Int())

svc_validation = Service(name="test-validation", path="/test-validation")


@svc_validation.post(schema=ListSchema)
def post(request):
    return {"test": "succeeded"}


config = Configurator()
config.include("cornice")
config.scan()
app = config.make_wsgi_app()

client = TestApp(app)

# Throws an exception
# AttributeError: 'Sequence' object has no attribute 'unknown'
client.post_json('/test-validation', {'key': [1, 2, 3]})
```

Traceback:
```python
  File "/venvs/cornice-test/src/cornice/cornice/service.py", line 495, in wrapper
    validate_colander_schema(args['schema'], request)
  File "/venvs/cornice-test/src/cornice/cornice/schemas.py", line 151, in validate_colander_schema
    if schema.colander_schema.typ.unknown == 'raise':
AttributeError: 'Sequence' object has no attribute 'unknown'
```

Somewhat related: https://github.com/mozilla-services/cornice/issues/249

**Comment by tisdall** [comment]
> Essentially this means anything other than a colander.MappingSchema.

Not exactly true...
```
>>> import colander
>>> x = colander.MappingSchema(colander.Sequence())
>>> x.typ
<colander.Sequence object at 0x7fb908fc6208>
>>> x.typ.unknown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Sequence' object has no attribute 'unknown'
>>> 
```

#309 fixes this issue

**Comment by leplatrem** [comment]
Schema typing was reworked in Cornice 2.0 (current master), and this may not apply anymore. Please reopen if your usecase is not covered by the new API. Thanks!
